dist: xenial
language: python
python: "3.6"

stages:
  - name: static analysis
  - name: test
  - name: deploy to pypi
    if: type = push AND tag =~ ^\d+\.\d+\.\d+

jobs:
  include:
    - stage: static analysis
      env: TOXENV=flake8

    - stage: static analysis
      env: TOXENV=mypy

    - &test
      stage: test
      env: TOXENV=pypy3
      python: pypy3.5-6.0
      after_success:
        - pip install coveralls
        - coveralls

    - <<: *test
      env: TOXENV=py35
      python: "3.5.2"

    - <<: *test
      env: TOXENV=py36
      python: "3.6"

    - <<: *test
      env: TOXENV=py37
      python: "3.7"

    - stage: deploy to pypi
      install: true
      script: skip
      deploy:
        provider: pypi
        user: agronholm
        password:
          secure: 6BLcxekzVRvabI7xGH5G0z+tFE90Ql5PsfiszxVe+SSvuT9Cqbswk79geRAW4XPcTISncMrsETYQy/kbbZhU6TICfbEdZ2yh+rOIJWGs6oVFgRl8fZNja+rjKtBlQ7WRlL+aH60XLHKwrmWxFG5aU1VkZyKS+mq79ZtfUHJBT9Y6yWsLVwDjZ2tm1EHZIxeFrX87iBztzb8rJV26XRTocNqoTHf0iG1b6zP+CXEYrTfHjLfpXwSdVqD8n5L11fCnpjQ1ySU2FoqVedwsNIQcVYIEYVKTySLz5jwLDKk/0YjVvIwVF0qFn5HbX38gL7mOJhPxrIDlckTSl4SMY4bmljn19r87nIaVdVIvZV5wN8of+bLYoQztY2oEYm9M7LnkLr01tLJut90k/FDMvXnqGsb1o2W8Acht5V1bvY+o6sRWPMPCiEg4fQgKs1bUZxlRhYqCWmavR6AdKmKlQozyezvMl0pfs4FZVBM6dSK3zfzboktE3B+Z1J4MVuQlGC1a4+6hKXYxqUCB1gDxLjEsaKLNoBShrAQRNuLM+QuySCz0c5v8F+VEEPuLJRRTNcJ0zEr91DjRMLZat2Zn4UUufTsEzh8+4F3ur3PiCSfoxFsuWBL3IE8TlVNrn7R9gYwamuE6f8BnQnGwN/9kKPNPqI/MERZjGfOMGosjzIOGYKE=
        distributions: sdist bdist_wheel
        on:
          tags: true
          repo: asphalt-framework/asphalt

install: pip install tox

script: tox

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aa5a289b7a0df8aefd68
